name: Build

on: [push]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1

            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1
      
            - name: Navigate to Workspace
              run: cd $GITHUB_WORKSPACE

            - name: Create Build Directory
              run: mkdir _build
              
            - name: Restore Packages
              run: nuget restore SampleWebAPI.sln
              
            - name: Build Solution
              run: |
                msbuild.exe SampleWebAPI.sln /nologo /nr:false /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
