name: Build

on: [push]

jobs:
    build:
        # Do not upgrade to latest, 2022 will not compile natively.
        runs-on: windows-2019
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1

            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1
      
            - name: Navigate to Workspace
              run: cd $GITHUB_WORKSPACE

            - name: Create Build Directory
              run: mkdir _build
              
            - name: Restore Packages
              run: nuget restore SampleWebAPI.sln
              
            - name: Build Solution
              run: |
                ls
                pwd
                msbuild.exe SampleWebAPI.sln /nologo /nr:false /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
                ls
                cd SampleWebAPI/bin
                ls
                cd ..
                cd obj\Release\
                ls
            
            #- name: Upload artifact
            #  uses: actions/upload-artifact@v3
            #  with:
            #    name: SampleWebAPI
            #    path: "./SampleWebAPI/bin" 
